- hosts: all
  sudo: yes

  vars_files:
    - ../vars/mongodb.yml

  tasks:
    - include: ../tasks/mongodb.yml

    - name: MongoDB | Restart server
      service:
        name: mongod
        state: restarted
