- hosts: all
  sudo: yes

  vars_files:
    - ../vars/mysql.yml

  tasks:
    - include: ../tasks/mysql.yml

    - name: MySQL | Restart server
      service:
        name: mysql
        state: restarted
